export const ActionTypes = {
    GET_BOOKS: "GET_BOOKS",

    SET_BOOK: "SET_BOOK",

    GET_ORDER_DETAILS: "GET_ORDER_DETAILS",

    SET_ORDER_DETAILS: "SET_ORDER_DETAILS",

    CHECKOUT: "CHECKOUT",

    GET_CART: "GET_CART",

    ADD_TO_CART: "ADD_TO_CART",

    REMOVE_FROM_CART: "REMOVE_FROM_CART",

    CLEAR_CART: "CLEAR_CART",

    INC_COUNT: "INC_COUNT",

    DEC_COUNT: "DEC_COUNT"
}